backport: epochly flush logic
ingenuity-build/quicksilver pull request #424
Opened 2023-05-10 22:00 UTC by ajansari95

## 1. Summary
Fixes # (issue)
backport: flush pending delegations

## 2.Type of change

- [x ] New feature (non-breaking change which adds functionality)

## 3. Implementation details
- flushes pending delegations over `day` epoch
- clears stale receipts

## 4. How to test/use

## 5. Checklist

- [ ] Does the Readme need to be updated?

## 6. Limitations (optional)

## 7. Future Work (optional)

2023-05-10 22:10 UTC, joe-bowman approved these changes
~~lgtm~~

2023-05-10 22:17 UTC, joe-bowman commented on x/interchainstaking/keeper/hooks.go
> +			addressBytes, err := utils.AccAddressFromBech32(zone.DelegationAddress.Address, zone.AccountPrefix)
wrap the below in `if zone.DelegationAddress != nil` as we cannot guarantee it will be non-nil when an epoch passes

2023-05-10 22:18 UTC, joe-bowman requested changes
check for non-nil delegationAddress

2023-05-10 22:18 UTC, joe-bowman requested changes
check for non-nil delegationAddress

2023-05-10 23:05 UTC, aljo242 approved these changes

2023-05-11 08:33 UTC, joe-bowman approved these changes
lgtm

2023-05-11 08:33 UTC, merged