Remove ProtocolData proposal
ingenuity-build/quicksilver pull request #481
Opened 2023-07-02 22:00 UTC by joe-bowman

## 1. Summary
Fixes QCK-486

## 2.Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 3. Implementation details

Add proposal for removing protocol data by key.

2023-07-03 07:48 UTC, ajansari95 commented on x/participationrewards/types/msgs.go
> +
```suggestion

```

2023-07-03 07:49 UTC, ajansari95 approved these changes
lgtm

2023-07-03 11:14 UTC, muku314115 approved these changes

2023-07-03 12:04 UTC, aljo242 requested changes

2023-07-03 12:04 UTC, aljo242 commented on x/participationrewards/types/msgs.go
> +func (msg MsgGovRemoveProtocolData) ValidateBasic() error { return nil }
Let's add address validation here for `authority`.

2023-07-04 09:32 UTC, joe-bowman commented on x/participationrewards/types/msgs.go
> +// NewMsgGovCloseChannel - construct a msg to update signalled intent.
```suggestion
// NewMsgGovRemoveProtocolData - construct a msg to update signalled intent.
```

2023-07-04 09:32 UTC, joe-bowman commented on x/participationrewards/types/msgs.go
> +// NewMsgGovCloseChannel - construct a msg to update signalled intent.
fix comment copypasta

2023-07-04 09:33 UTC, joe-bowman commented on x/participationrewards/types/msgs.go
> +// NewMsgGovRemoveProtocolData - construct a msg to update signalled intent.
```suggestion
// NewMsgGovRemoveProtocolData - construct a governance proposal msg to remove protocoldata by key.
```

2023-07-04 09:34 UTC, joe-bowman commented on x/participationrewards/types/msgs_test.go
> +				err := fmt.Errorf("MsgSubmitClaim.GetSigners() = %v, want %v", got, tt.want)
```suggestion
				err := fmt.Errorf("MsgGovRemoveProtocolData.GetSigners() = %v, want %v", got, tt.want)
```

2023-07-04 09:50 UTC, ajansari95 submitted a review, later dismissed
lgtm

2023-07-04 10:34 UTC, muku314115 approved these changes
lgtm

2023-07-04 11:01 UTC, ajansari95 approved these changes
lgtm

2023-07-04 11:01 UTC, merged