chore: clean up subzones code
ingenuity-build/quicksilver pull request #502
Opened 2023-07-13 17:43 UTC by aljo242

Clean up subzones code by renaming helpers:
- `zone.ChainID()` -> `zone.BaseChainID()`
- `zone.ID()` -> `zone.ZoneID()` (redundant i know, but it is clearer.

Refactor functions that receive ID strings to receive `*Zone` and get the ID string internally.  This way, there are significantly less ID function calls throughout the codebase which was getting confusing.

2023-07-13 20:02 UTC, joe-bowman commented on x/interchainstaking/types/accounts.go
> +	return z.ZoneID() + ".deposit"
These suffixes exist as constants already.

2023-07-13 20:03 UTC, joe-bowman requested changes
Just the suffix consts, else lgtm

2023-07-14 12:20 UTC, aljo242 commented on x/interchainstaking/types/accounts.go
> +	return z.ZoneID() + ".deposit"
https://github.com/ingenuity-build/quicksilver/pull/502/commits/f22910740f719ccde6c6a1c6d354a96bf6cab222

2023-07-14 12:26 UTC, joe-bowman submitted a review, later dismissed
lgtm, ty

2023-07-14 20:54 UTC, joe-bowman approved these changes
lgtm

2023-07-17 14:52 UTC, ajansari95 approved these changes
lgtm

2023-07-17 14:52 UTC, merged